---
root: true

plugins:
  - jest
  - babel
  - prettier

env:
  node: true
  jest: true
  browser: true

parser: '@babel/eslint-parser'

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:prettier/recommended'

rules:
  no-console: 0
